/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CargoDAO;
import Model.Funcionario;
import Control.FuncionarioDAO;
import Control.HorariosDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;

public class CadastroDeFuncionario extends javax.swing.JFrame {
 boolean ok ;
    
    public void preencherComboBoxCargo(JComboBox<String> comboBox) {
     CargoDAO cargobox = new CargoDAO();
     List<String> cargos = cargobox.ListarCargos();
     comboBox.removeAllItems();
        for (String cargoItem : cargos) {
         comboBox.addItem(cargoItem);
        }
    }
      
    public void preencherComboBoxTurno(JComboBox<String> comboBox) {
     HorariosDAO turnobox = new HorariosDAO();
     List<String> turno = turnobox.ListarHorarios();
     comboBox.removeAllItems();
        for (String turnoItem : turno) {
         comboBox.addItem(turnoItem);
        }
         
    }
    
    public CadastroDeFuncionario() {
     initComponents();
     this.preencherComboBoxCargo(jComboBoxCargo);
     this.preencherComboBoxTurno(jComboBoxTurno);
     jComboBoxTurno.setEnabled(false);
     
     // Detectar clique com MouseListener
        jComboBoxCargo.addPopupMenuListener(new PopupMenuListener() {
         @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
             jComboBoxTurno.setEnabled(true);          
            }
         @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) { }
         @Override
            public void popupMenuCanceled(PopupMenuEvent e) { }   
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cadastrar = new javax.swing.JButton();
        jTextFieldnome = new javax.swing.JTextField();
        jFormattedTextFieldAdmissao = new javax.swing.JFormattedTextField();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldHorasTrabalho = new javax.swing.JLabel();
        jFormattedTextFieldSalario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Data de Admissão:");

        jLabel4.setText("Cargo:");

        jLabel5.setText("Salário Mensal:");

        jLabel7.setText("Horario de Trabalho:");

        Cadastrar.setText("CADASTRAR");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        jTextFieldnome.setText("Nome de Teste");

        try {
            jFormattedTextFieldAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldAdmissao.setText("2020-10-10");

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCargo.setToolTipText("ESCOLHA");
        jComboBoxCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCargoItemStateChanged(evt);
            }
        });

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setText("222.222.222-22");

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("VOLTAR");

        jLabel6.setText("Cadastrar Funcionario");

        jLabel8.setText("Carga Horaria mensal:");

        jFormattedTextFieldHorasTrabalho.setText("jLabel9");

        jFormattedTextFieldSalario.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldHorasTrabalho)
                                    .addComponent(jFormattedTextFieldSalario)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Cadastrar)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldHorasTrabalho))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldSalario))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar)
                    .addComponent(jButton2))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
     ok = true;
     Funcionario Func = new Funcionario();
     FuncionarioDAO FuncDAO = new FuncionarioDAO();
     
        if(jTextFieldnome.getText().isEmpty()){
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "O Campo NOME é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
         jTextFieldnome.requestFocusInWindow();
         ok = false;
        }    
        
        if(jFormattedTextFieldCPF.getText().isEmpty()){
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "O Campo CPF é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
         jFormattedTextFieldCPF.requestFocusInWindow();
         ok = false;
        }
        
        if(jFormattedTextFieldAdmissao.getText().isEmpty()){
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "O Campo DATA DE ADMISSÃO é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
         jFormattedTextFieldAdmissao.requestFocusInWindow();
         ok = false;
        }
        
        if(jFormattedTextFieldSalario.getText().isEmpty()){
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "O Campo SALARIO é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
         //aa.requestFocusInWindow();
         ok = false;
        }
        
        if(jFormattedTextFieldHorasTrabalho.getText().isEmpty()){
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "O Campo HORAS DE TRABALHO é obrigatório!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
       //  aa.requestFocusInWindow();
         ok = false;
        }
        
        if(!jComboBoxTurno.isEnabled()){
         ok = false;
        }
       
     LocalDate Admissao = LocalDate.parse(jFormattedTextFieldAdmissao.getText(), DateTimeFormatter.ISO_DATE);
     float SalarioHora;
        if(ok){  
         Func.setNome(jTextFieldnome.getText());
         Func.setCPF(jFormattedTextFieldCPF.getText());
         Func.setDataAdmissao(Admissao);
         Func.setTurno(jComboBoxTurno.getSelectedIndex()+1);
         Func.setCargo(jComboBoxCargo.getSelectedIndex()+1);
         Func.setSalarioBase(SalarioTot);
         Func.setHorasDeTrabalho(ValorHora);
         // SalarioHora = Float.valueOf(aa.getText()); //,Integer.valueOf(jFormattedTextFieldHorasTrabalho.getText()); 
          FuncDAO.SalvarFuncionario(Func);
         
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "CADASTRO SALVO!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
         ListaFuncionarios tela = new ListaFuncionarios();
         this.dispose();
         tela.setVisible(true);
        }else{
         JOptionPane.showMessageDialog(CadastroDeFuncionario.this, "ERRO NO CADASTRO!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CadastrarActionPerformed
   int ValorHora=0;
   Float HorasTrabalho, SalarioTot ;
    
    private void jComboBoxCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCargoItemStateChanged
        if (jComboBoxCargo.getSelectedIndex() == 4 ){     
         this.preencherComboBoxTurno(jComboBoxTurno);
         jComboBoxTurno.removeItem("MANHÃ");
         jComboBoxTurno.removeItem("TARDE");
         jComboBoxTurno.removeItem("NOITE");
         HorasTrabalho = 40.0f ;
         ValorHora = 15;
        } else {     
          this.preencherComboBoxTurno(jComboBoxTurno);
          jComboBoxTurno.removeItem("SAB");
          jComboBoxTurno.removeItem("DOM");
          HorasTrabalho = 160.0f;
          
          switch(jComboBoxCargo.getSelectedIndex()){
              case 0:  ValorHora = 50; break; 
              case 1:  ValorHora = 40; break;
              case 2:  ValorHora = 30; break;
              case 3:  ValorHora = 20; break;
          }    
          }
        SalarioTot = HorasTrabalho * ValorHora;
        jFormattedTextFieldHorasTrabalho.setText(String.valueOf(HorasTrabalho));
        jFormattedTextFieldSalario.setText(String.valueOf(SalarioTot));
        
    }//GEN-LAST:event_jComboBoxCargoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JFormattedTextField jFormattedTextFieldAdmissao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JLabel jFormattedTextFieldHorasTrabalho;
    private javax.swing.JLabel jFormattedTextFieldSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables
}
