/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.FolhaDePagamentoDAO;
import Control.FuncionarioDAO;
import Model.FolhaDePagamento;
import Model.Funcionario;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.JOptionPane;

public class CalcularSalarioBruto extends javax.swing.JFrame {
 Funcionario func;
 FuncionarioDAO FuncDAO = new FuncionarioDAO();
 int IDSelecionado;
 Locale ptBr = new Locale("pt", "BR");
 String SalarioString ; 
 Float SalarioAjstDias;
 int DiasTrabalhoMensal;
 
    public CalcularSalarioBruto() {
     initComponents();
    }

    public CalcularSalarioBruto(int  ID) {   
     initComponents();
     jCheckBox1.setSelected(true);   
     CalcularSalarioBruto.this.setLocation(500, 300);
     IDSelecionado = ID;
     
     preencherDados();
     VerificarFalta();
     SalarioString  = NumberFormat.getCurrencyInstance(ptBr).format(func.getSalarioBase());
     DiasTrabalhoMensal = Integer.valueOf(jTFDiasTrabalho.getText());
     SalarioAjstDias = func.getSalarioBase();
    }
    
    public int DefinirSalarioBruto( Float valor){
     int Nivel = 0;
     jLSalarioAtlzd.setText(String.valueOf(valor));
     Nivel++;
     return Nivel;
    }
        
   
    public void preencherDados(){
     func = FuncDAO.CarregarCalculoSalarios(IDSelecionado);
     jLNOME.setText(func.getNome());
     jTFcargo.setText(func.getCargoDesc());
     jLSalarioBase.setText(String.valueOf(func.getSalarioBase()));
     jTFturno.setText(func.getTurnoDesc());
        if(func.getTurno()== 3){
         jBNoturno.setBackground(Color.red);
        }  
    }
    
    public void VerificarFalta(){
        if(jCheckBox1.isSelected()){ 
            if(func.getTurno() <= 3){
             jTFDiasTrabalho.setText(String.valueOf(20));
             jTFDiasTrabalho.setEnabled(false);
             Float Valor = Float.valueOf(jLSalarioBase.getText());
             this.DefinirSalarioBruto(Valor);
            }else if(func.getTurno() == 4 || func.getTurno() == 5)  {
             jTFDiasTrabalho.setText(String.valueOf(8)); 
             jTFDiasTrabalho.setEnabled(false);
             Float Valor = Float.valueOf(this.converterParaNumero(SalarioString));
             this.DefinirSalarioBruto(Valor);
            }
        }else{
         jTFDiasTrabalho.setEnabled(true);
         jTFDiasTrabalho.setEditable(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNOME = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFDiasTrabalho = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CriarPagamento = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDiasExtras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonAddDiasExtras = new javax.swing.JButton();
        jBNoturno = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLSalarioBase = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTFcargo = new javax.swing.JLabel();
        jLSalarioAtlzd = new javax.swing.JLabel();
        jButtonAplicarFalta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFturno = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNOME.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLNOME.setText("NOME DE FUNCIONARIO");

        jLabel2.setText("Calcular salario");

        jLabel3.setText("Base salarial:");

        jLabel4.setText("Dias Extras:");

        jTFDiasTrabalho.setText("00");

        jLabel8.setText("Dias Trabalhados:");

        CriarPagamento.setText("SALVAR");
        CriarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarPagamentoActionPerformed(evt);
            }
        });

        jButton2.setText("VOLTAR");

        jLabel9.setText("Adicional Noturno:");

        jTextFieldDiasExtras.setText("0");

        jLabel10.setText("Insalubridade:");

        jTextField6.setText("DESCONTOXX");

        jLabel11.setText("Periculosidade:");

        jTextField7.setText("DESCONTOXX");

        jLabel12.setText("Salario Bruto atualizado: ");

        jButtonAddDiasExtras.setText("APLICAR");
        jButtonAddDiasExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDiasExtrasActionPerformed(evt);
            }
        });

        jBNoturno.setText("APLICAR");
        jBNoturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNoturnoActionPerformed(evt);
            }
        });

        jButton5.setText("APLICAR");

        jButton6.setText("APLICAR");

        jButton7.setText("APLICAR TODOS");

        jLSalarioBase.setText("VALOR SALARIO ");

        jCheckBox1.setText("Sem Faltas");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jTFcargo.setText("CARGO");

        jLSalarioAtlzd.setText("Salario atualizado");

        jButtonAplicarFalta.setText("APLICAR");
        jButtonAplicarFalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarFaltaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cargo:");

        jLabel6.setText("Turno de trabalho:");

        jTFturno.setText("TURNO");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("22:00 as 05:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLSalarioAtlzd)
                        .addGap(87, 87, 87)
                        .addComponent(jButton7))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFcargo)
                                .addComponent(jLabel5))
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jTFturno))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLSalarioBase)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTFDiasTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonAplicarFalta))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton6))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDiasExtras))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonAddDiasExtras))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(jBNoturno)))))
                            .addGap(13, 13, 13))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CriarPagamento)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLNOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFcargo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFturno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTFDiasTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)
                            .addComponent(jButtonAplicarFalta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLSalarioBase)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDiasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddDiasExtras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBNoturno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLSalarioAtlzd)
                    .addComponent(jButton7))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarPagamento)
                    .addComponent(jButton2))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
     VerificarFalta();
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void CriarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarPagamentoActionPerformed
     FolhaDePagamentoDAO FolhaDAO = new FolhaDePagamentoDAO();
     FolhaDePagamento Folha = new FolhaDePagamento();
     Folha.setId(1);
     Folha.setId_funcionario(IDSelecionado);
     Float Valor = Float.valueOf(jLSalarioAtlzd.getText());
     Folha.setValorPago(Valor);
     FolhaDAO.AbrirFolhaDePagamento(Folha);
     JOptionPane.showMessageDialog(CalcularSalarioBruto.this, "A folha de de XXXXXXXXXXXXXXXXX foi Aberta!","INFORMAÇãO",JOptionPane.INFORMATION_MESSAGE);         
    }//GEN-LAST:event_CriarPagamentoActionPerformed

    private void jButtonAplicarFaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarFaltaActionPerformed
        // TODO add your handling code here:
       
        
      SalarioAjstDias = (Float.valueOf(jLSalarioBase.getText()) /  Float.valueOf(DiasTrabalhoMensal)) * Float.valueOf(jTFDiasTrabalho.getText());
      // System.out.print(DiasTrabalhoMensal);
      // System.out.print(jLSalarioBase.getText());
       //System.out.print(jTFDiasTrabalho.getText());
       
      //VLRapagar = (Salario BASE * Dias trabalho Base) / dias trabalhados; 
      jLSalarioAtlzd.setText(String.valueOf(SalarioAjstDias));
    }//GEN-LAST:event_jButtonAplicarFaltaActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jButtonAplicarFalta.setEnabled(false);
        }else{
            jButtonAplicarFalta.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jButtonAddDiasExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDiasExtrasActionPerformed
        // TODO add your handling code here:
     Float SalarioAjusteExtras =  (Float.valueOf(jLSalarioBase.getText()) /  Float.valueOf(DiasTrabalhoMensal)) * Float.valueOf(jTextFieldDiasExtras.getText());   
      Float SalarioAtualizado2 = SalarioAjstDias + SalarioAjusteExtras;
      jLSalarioAtlzd.setText(String.valueOf(SalarioAtualizado2));
    }//GEN-LAST:event_jButtonAddDiasExtrasActionPerformed

    private void jBNoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNoturnoActionPerformed
        // TODO add your handling code here:
       int horasNormaisPorDia = 8; // Total de horas trabalhadas por dia
        int horasNoturnas = 5; // Horas aptas para adicional noturno
        Float adicionalPercentual = 0.20f; // 20% de adicional noturno
        int diasNoMes = 20;  
        
      Float ValorHora =   Float.valueOf(jLSalarioBase.getText()) /  (diasNoMes * horasNormaisPorDia);
     
//  Float HoraNtDesc = ValorHora * 100;
    //  Float HoraNtA = Float.valueOf(jLSalarioAtlzd.getText()) - HoraNtDesc ;
    int diastrabalhados = horasNormaisPorDia + Integer.valueOf(jTextFieldDiasExtras.getText());
      Float ValorHoraNoturna = (ValorHora * horasNoturnas) * adicionalPercentual * diastrabalhados;
   //   Float ValorpagoNoturno = HoraNtA + (ValorHoraNoturna * 100);
   System.out.print(ValorHoraNoturna);
      Float SalarioAtualizado3 = Float.valueOf(jLSalarioAtlzd.getText()) + ValorHoraNoturna;
      jLSalarioAtlzd.setText(String.valueOf(SalarioAtualizado3));
        // Horas Noturna/dia = 5 - dias trabalho no mes = 20 5*20=100 horas noturnas
    }//GEN-LAST:event_jBNoturnoActionPerformed

    public static Float converterParaNumero(String valor) {
        try {
            // Remove espaços extras e formata para moeda padrão brasileira
            NumberFormat format = NumberFormat.getInstance(new Locale("pt", "BR"));
            return format.parse(valor.replace("R$", "").trim()).floatValue();
        } catch (ParseException e) {
            throw new NumberFormatException("Formato inválido: " + valor);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularSalarioBruto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularSalarioBruto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularSalarioBruto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularSalarioBruto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularSalarioBruto().setVisible(true);    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarPagamento;
    private javax.swing.JButton jBNoturno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAddDiasExtras;
    private javax.swing.JButton jButtonAplicarFalta;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLNOME;
    private javax.swing.JLabel jLSalarioAtlzd;
    private javax.swing.JLabel jLSalarioBase;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFDiasTrabalho;
    private javax.swing.JLabel jTFcargo;
    private javax.swing.JLabel jTFturno;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldDiasExtras;
    // End of variables declaration//GEN-END:variables
}
